# Generated by Django 2.0.5 on 2018-07-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180725_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoPath',
            field=models.TextField(default='https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4', max_length=10000),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoQuality',
            field=models.CharField(default='576', max_length=200),
        ),
    ]
