# Generated by Django 2.0.5 on 2018-07-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180725_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='subtitlePath',
            field=models.TextField(default='https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-HD.en.vtt', max_length=10000),
        ),
    ]
