# Generated by Django 2.0.5 on 2018-07-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180725_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='videoName',
        ),
    ]
