# Generated by Django 2.0.5 on 2018-07-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_subtitle_videoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='videoName',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.Video'),
            preserve_default=False,
        ),
    ]
