# Generated by Django 2.0.5 on 2018-07-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_subtitle_videoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='subtitleFormat',
            field=models.CharField(default='vtt', max_length=100),
        ),
    ]
