# Generated by Django 2.0.5 on 2018-07-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_subtitle_subtitleformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='endTime',
            field=models.CharField(default='00:00:00', max_length=100),
        ),
        migrations.AddField(
            model_name='video',
            name='startTime',
            field=models.CharField(default='00:00:00', max_length=100),
        ),
    ]
