# Generated by Django 2.0.5 on 2018-07-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180728_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='endTime',
            field=models.CharField(default='00:00:00.000', max_length=100),
        ),
        migrations.AlterField(
            model_name='video',
            name='startTime',
            field=models.CharField(default='00:00:00.000', max_length=100),
        ),
    ]
