# Generated by Django 2.0.5 on 2018-07-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180728_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='video',
            name='startTime',
        ),
    ]
