# Generated by Django 2.1 on 2018-08-02 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180728_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='videoName',
        ),
        migrations.DeleteModel(
            name='Subtitle',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
