# Generated by Django 2.1 on 2018-08-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0012_auto_20180802_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('videoFormat', models.CharField(default='video/mp4', max_length=200)),
                ('videoQuality', models.CharField(default='576', max_length=200)),
                ('videoPath', models.TextField(default='https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-576p.mp4', max_length=10000)),
            ],
        ),
    ]
