# Generated by Django 2.1 on 2018-08-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default='View_From_A_Blue_Moon_Trailer', max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoPath',
            field=models.TextField(default='/home/mahdi/Desktop/Desktop/searchInVideos/django-apps/testsite/media/videos/View_From_A_Blue_Moon_Trailer-576p.mp4', max_length=10000),
        ),
    ]
